[package]
name = "Cross-Booster"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.3"
eframe = "0.33.3"
image = "0.25"
encoding_rs = "0.8"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
